name: ghaith
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.1+3

environment:
  sdk: ">=2.18.2 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  adhan: null
  after_layout: ^1.2.0
  animate_do: null
  animations: null
  arabic_roman_conv: null
  audio_meta: ^1.2.0
  audio_session: null
  auto_animated_list: ^2.0.0
  auto_size_text: ^3.0.0
  azlistview: ^2.0.0
  back_button_interceptor: null
  cached_network_image: null
  chewie: null
  contextmenu: ^3.0.0
  cupertino_icons: ^1.0.2
  dio: null
  easy_container: null
  easy_localization: ^3.0.3
  flutter:
    sdk: flutter
  flutter_bloc: null
  flutter_colorpicker: null
  flutter_displaymode: ^0.6.0
  flutter_html: null
  flutter_keyboard_visibility: ^6.0.0
  flutter_local_notifications: ^19.4.0
  flutter_overlay_window: null
  flutter_screenutil: null
  flutter_svg: null
  fluttericon: null
  fluttertoast: null
  geocoding: null
  geolocator: null
  group_list_view: ^1.1.1
  hijri: null
  hive: null
  http: ^1.5.0
  iconsax: null
  image_gallery_saver_plus: ^4.0.1
  in_app_review: null
  in_app_update: null
  indexed_list_view: ^4.0.0
  intl: null
  jhijri_picker: null
  just_audio: any
  just_audio_background: any
  lottie: null
  media_store_plus: null
  modal_bottom_sheet: ^3.0.0
  path_provider: ^2.1.5
  permission_handler: null
  quran:
    path: ./quran-1.2.2
  radio_player: null
  screenshot: ^3.0.0
  scrollable_positioned_list: null
  share_plus: ^11.0.0
  shared_preferences: null
  shimmer: ^3.0.0
  simple_annimated_staggered: ^0.0.3
  snapx_scroll_physics: ^1.0.1
  string_validator: null
  superellipse_shape: null
  syncfusion_flutter_sliders: null
  tiktoklikescroller: null
  visibility_detector: null
  workmanager: null

dev_dependencies:
  flutter_launcher_icons: null
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
dependency_overrides:
  win32: ^5.5.4
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/json/
    - assets/translations/

  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: AmiriQuran
      fonts:
        - asset: assets/fonts/AmiriQuran-Regular.ttf

    - family: Taha
      fonts:
        - asset: assets/fonts/taha.ttf
    - family: me
      fonts:
        - asset: assets/fonts/me_quran.ttf

    - family: UthmanicHafs13
      fonts:
        - asset: assets/fonts/UthmanicHafs1 Ver13.otf

    - family: "qaloon"
      fonts:
        - asset: assets/fonts/qaloon.ttf

    - family: "pdsm"
      fonts:
        - asset: assets/fonts/pdms.otf
    - family: cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
    - family: "noor ehuda"
      fonts:
        - asset: assets/fonts/noorehuda-org.ttf

    - family: "hafs-nastaleeq-ver10-org"
      fonts:
        - asset: assets/fonts/hafs-nastaleeq-ver10-org.otf
    - family: "hafs-smart-07"
      fonts:
        - asset: assets/fonts/hafs-smart-07.woff

    - family: "jomhuria-regular-full-org"
      fonts:
        - asset: assets/fonts/jomhuria-regular-full-org.ttf

    - family: "mada-regular-full"
      fonts:
        - asset: assets/fonts/mada-regular-full.ttf
    - family: "markazi-text-regular-full-org"
      fonts:
        - asset: assets/fonts/markazi-text-regular-full-org.ttf
    - family: "noto-kufi-arabic-regular-full"
      fonts:
        - asset: assets/fonts/noto-kufi-arabic-regular-full.ttf

    - family: "qumbul-v7-full"
      fonts:
        - asset: assets/fonts/qumbul-v7-full.ttf
    - family: "qur-std"
      fonts:
        - asset: assets/fonts/qur-std.ttf

    - family: "shorooq-full-org"
      fonts:
        - asset: assets/fonts/shorooq-full-org.ttf

    - family: "arsura"
      fonts:
        - asset: assets/fonts/arsura.ttf

    - family: "KFGQPC Uthmanic Script HAFS Regular"
      fonts:
        - asset: assets/fonts/KFGQPC Uthmanic Script HAFS Regular.otf
    - family: "roboto"
      fonts:
        - asset: assets/fonts/roboto.ttf
